
package webservice.jobservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JobServiceImplService", targetNamespace = "http://impl.jobservice.webservice/", wsdlLocation = "http://localhost:9991/ws/jobservice?WSDL")
public class JobServiceImplService
    extends Service
{

    private final static URL JOBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.jobservice.client.JobServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.jobservice.client.JobServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9991/ws/jobservice?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9991/ws/jobservice?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        JOBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public JobServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobServiceImplService() {
        super(JOBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.jobservice.webservice/", "JobServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns JobService
     */
    @WebEndpoint(name = "JobServiceImplPort")
    public JobService getJobServiceImplPort() {
        return super.getPort(new QName("http://impl.jobservice.webservice/", "JobServiceImplPort"), JobService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobService
     */
    @WebEndpoint(name = "JobServiceImplPort")
    public JobService getJobServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.jobservice.webservice/", "JobServiceImplPort"), JobService.class, features);
    }

}
