
package webservice.tryfourth.phoneclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PhoneManager", targetNamespace = "http://dd.ws.it.cn", wsdlLocation = "http://127.0.0.1:8888/ws/phoneService?WSDL")
public class PhoneManager
    extends Service
{

    private final static URL PHONEMANAGER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.tryfourth.phoneclient.PhoneManager.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.tryfourth.phoneclient.PhoneManager.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8888/ws/phoneService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8888/ws/phoneService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PHONEMANAGER_WSDL_LOCATION = url;
    }

    public PhoneManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneManager() {
        super(PHONEMANAGER_WSDL_LOCATION, new QName("http://dd.ws.it.cn", "PhoneManager"));
    }

    /**
     * 
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort() {
        return super.getPort(new QName("http://dd.ws.it.cn", "PhoneServicePort"), PhoneService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dd.ws.it.cn", "PhoneServicePort"), PhoneService.class, features);
    }

}
