
package webservice.trysecond;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StudentServiceImp", targetNamespace = "http://trysecond.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentServiceImp {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://trysecond.webservice/", className = "webservice.trysecond.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://trysecond.webservice/", className = "webservice.trysecond.SayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
