
package webservice.trythird;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BossService", targetNamespace = "http://trythird.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BossService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayBoss", targetNamespace = "http://trythird.webservice/", className = "webservice.trythird.SayBoss")
    @ResponseWrapper(localName = "sayBossResponse", targetNamespace = "http://trythird.webservice/", className = "webservice.trythird.SayBossResponse")
    public String sayBoss(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
