
package webservice.tryfirst;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserServiceImplService", targetNamespace = "http://tryfirst.webservice/", wsdlLocation = "http://localhost:9998/user?wsdl")
public class UserServiceImplService
    extends Service
{

    private final static URL USERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.tryfirst.UserServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.tryfirst.UserServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9998/user?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9998/user?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public UserServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceImplService() {
        super(USERSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://tryfirst.webservice/", "UserServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns UserServiceImpl
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserServiceImpl getUserServiceImplPort() {
        return super.getPort(new QName("http://tryfirst.webservice/", "UserServiceImplPort"), UserServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceImpl
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserServiceImpl getUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tryfirst.webservice/", "UserServiceImplPort"), UserServiceImpl.class, features);
    }

}
